os.execute("del BaseController")
os.execute("del DC")
print("getting BaseController")
os.execute("wget -f -r https://github.com/jaytherunaway/Opencomputers-programes/raw/main/BaseController")
print("")
print("getting DroneController")
os.execute("wget -f -r https://github.com/jaytherunaway/Opencomputers-programes/raw/main/DC")
print("Update Complete")
os.sleep(5)
os.execute("clear")
