print("getting BaseController")
os.execute("wget -f https://github.com/jaytherunaway/Opencomputers-programes/raw/main/BaseController")
print("")
print("getting DroneController")
os.execute("https://github.com/jaytherunaway/Opencomputers-programes/raw/main/DC")
print("Update Complete")
os.sleep(1)
os.execute("clear")
